# Generated by Django 3.2.15 on 2022-10-17 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221018_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='recipes.tag', verbose_name='Тэги'),
            preserve_default=False,
        ),
    ]
