# Generated by Django 3.2.15 on 2022-10-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20221022_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients_amount',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
