# Generated by Django 3.2.15 on 2022-10-27 16:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20221024_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_amount', to='recipes.ingredients_amount', verbose_name='Кол-во'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=150, verbose_name='Ед. изм.'),
        ),
        migrations.AlterField(
            model_name='ingredients_amount',
            name='amount',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время готовки'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together={('name', 'amount', 'measurement_unit')},
        ),
        migrations.AlterUniqueTogether(
            name='ingredients_amount',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ingredients_amount',
            name='ingredient',
        ),
    ]
