# Generated by Django 3.2.15 on 2022-10-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20221018_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='ingredients_amount',
            options={'verbose_name': 'Кол-во ингредиентов', 'verbose_name_plural': 'Кол-во ингредиентов'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.TextField(default=1, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
